### PR TITLE
Czech update for Flarum 0.1.0-beta.8

### PR DESCRIPTION
**Pull request by PepaR**
May you update, please?

### CODE REVIEW

**Comment by jficz** [comment]
Hi, thanks for the pull request! I'm afraid I can't merge it as seems to be encoded in ISO-8859-2 (or perhaps CP1250) but it should be in UTF-8.

**Comment by PepaR** [comment]
I reuploaded it with UTF -8. May you check it, please?

**Comment by jficz** [comment]
Sure, no prob, create a new pull request with new files and I'll do my best to get it there asap :)

**Comment by PepaR** [comment]
I did it. Thaks a lot for merging.

**Comment by PepaR** [comment]
Dobrý den, vzpomenete si na mě při chvilce s aktualizací češtiny pro Flarum, prosím?

**Pull request closed without merging**
