### PR TITLE
Czech update for Flarum 0.1.0-beta.8 (UTF-8)

### PR DESCRIPTION
**Pull request by PepaR**

### CODE REVIEW

**Comment by jficz** [comment]
The encoding is still wrong. See the diff, symbols like č and ř are encoded incorrectly.

**Comment by PepaR** [comment]
I resaved language files via notepad as UTF-8 and reuploaded it. May you check it, please?

**Comment by PepaR** [comment]
May I ask for e-mail contact, please? I'm beginner with GitHub and it will be more quickly to manage it.

**Comment by jficz** [comment]
no prob, now it's ok :) merged

Thanks for the contribution. If you're interested, I'd be happy to give the package to you.

**Comment by PepaR** [comment]
Thanks a lot. It will be fine, if you give the package to me.

**Comment by jficz** [comment]
Great, create your package at packagist.org and I will abandom mine in favour of yours.

**Pull request merged**
